### ISSUE TITLE
MFCC的feature_conf是什么在configs/ecapa_tdnn.yml文件里面

### ISSUE THREAD

**Issue by eeric** [yeyupiaoling/VoiceprintRecognition-Pytorch#43]

**Comment by yeyupiaoling** [comment]
```
preprocess_conf:
  # 音频预处理方法，支持：MelSpectrogram、Spectrogram、MFCC
  feature_method: 'MFCC'

# MFCC的参数，其他的预处理方法查看对应API设设置参数
feature_conf:
  sample_rate: 16000
  n_fft: 1024
  hop_length: 320
  win_length: 1024
  f_min: 50.0
  f_max: 14000.0
  n_mels: 64
  n_mfcc: 40
```
